# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(485, 397)
        Login.setMinimumSize(QtCore.QSize(485, 397))
        Login.setMaximumSize(QtCore.QSize(485, 397))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        Login.setFont(font)
        self.TitleLabel = TitleLabel(parent=Login)
        self.TitleLabel.setGeometry(QtCore.QRect(180, 70, 151, 31))
        self.TitleLabel.setMinimumSize(QtCore.QSize(151, 31))
        self.TitleLabel.setMaximumSize(QtCore.QSize(151, 31))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(-1)
        font.setBold(True)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.widget = QtWidgets.QWidget(parent=Login)
        self.widget.setGeometry(QtCore.QRect(130, 140, 241, 221))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(50, 10, 50, 10)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_login = PrimaryPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(131, 31))
        self.btn_login.setMaximumSize(QtCore.QSize(131, 31))
        self.btn_login.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_3.addWidget(self.btn_login)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LineEdit = LineEdit(parent=self.widget)
        self.LineEdit.setObjectName("LineEdit")
        self.verticalLayout.addWidget(self.LineEdit)
        self.PasswordLineEdit = PasswordLineEdit(parent=self.widget)
        self.PasswordLineEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.PasswordLineEdit.setPasswordVisible(False)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout.addWidget(self.PasswordLineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "汽车道闸控制系统"))
        self.TitleLabel.setText(_translate("Login", "管理员登录"))
        self.btn_login.setText(_translate("Login", "登录"))
        self.LineEdit.setPlaceholderText(_translate("Login", "Username"))
        self.PasswordLineEdit.setPlaceholderText(_translate("Login", "Password"))
from qfluentwidgets import LineEdit, PasswordLineEdit, PrimaryPushButton, TitleLabel
