# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 501)
        MainWindow.setMinimumSize(QtCore.QSize(624, 501))
        MainWindow.setMaximumSize(QtCore.QSize(624, 501))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.runsys = PrimaryPushButton(parent=self.centralwidget)
        self.runsys.setGeometry(QtCore.QRect(240, 360, 153, 32))
        self.runsys.setObjectName("runsys")
        self.TitleLabel = TitleLabel(parent=self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(200, 50, 231, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(21)
        font.setBold(True)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.mpass = PrimaryPushButton(parent=self.centralwidget)
        self.mpass.setGeometry(QtCore.QRect(240, 280, 153, 32))
        self.mpass.setObjectName("mpass")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 180, 401, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(parent=self.widget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.carLineEdit = LineEdit(parent=self.widget)
        self.carLineEdit.setObjectName("carLineEdit")
        self.horizontalLayout.addWidget(self.carLineEdit)
        self.addcar = PushButton(parent=self.widget)
        self.addcar.setObjectName("addcar")
        self.horizontalLayout.addWidget(self.addcar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "汽车道闸控制系统"))
        self.runsys.setText(_translate("MainWindow", "开启道闸控制系统"))
        self.TitleLabel.setText(_translate("MainWindow", "汽车道闸控制系统"))
        self.mpass.setText(_translate("MainWindow", "修改管理员密码"))
        self.BodyLabel.setText(_translate("MainWindow", "车牌号"))
        self.addcar.setText(_translate("MainWindow", "添加车辆"))
from qfluentwidgets import BodyLabel, LineEdit, PrimaryPushButton, PushButton, TitleLabel
