# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(531, 417)
        self.formLayout = QtWidgets.QFormLayout(Window)
        self.formLayout.setObjectName("formLayout")
        self.LargeTitleLabel = LargeTitleLabel(parent=Window)
        self.LargeTitleLabel.setMinimumSize(QtCore.QSize(507, 100))
        self.LargeTitleLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(30)
        font.setBold(False)
        self.LargeTitleLabel.setFont(font)
        self.LargeTitleLabel.setScaledContents(True)
        self.LargeTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.LargeTitleLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PasswordLineEdit = PasswordLineEdit(parent=Window)
        self.PasswordLineEdit.setClearButtonEnabled(False)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout.addWidget(self.PasswordLineEdit)
        self.LineEdit = LineEdit(parent=Window)
        self.LineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.LineEdit.setObjectName("LineEdit")
        self.verticalLayout.addWidget(self.LineEdit)
        self.PrimaryPushButton = PrimaryPushButton(parent=Window)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout.addWidget(self.PrimaryPushButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.verticalLayout)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "汽车道闸控制系统"))
        self.LargeTitleLabel.setText(_translate("Window", "欢迎来到汽车道闸控制系统"))
        self.PasswordLineEdit.setPlaceholderText(_translate("Window", "Password"))
        self.LineEdit.setPlaceholderText(_translate("Window", "Username"))
        self.PrimaryPushButton.setText(_translate("Window", "登录"))
from qfluentwidgets import LargeTitleLabel, LineEdit, PasswordLineEdit, PrimaryPushButton
